apiVersion: v1
kind: Service
metadata:
  name: eurostocks
  labels:
    app: eurostocks
spec:
  selector:
    app: eurostocks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer