apiVersion: v1
kind: Service
metadata:
  name: eurostocks-consumers
  labels:
    app: eurostocks-consumers
spec:
  selector:
    app: eurostocks-consumers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer