apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  ports:
    - name: http
      protocol: TCP
      port: 4566
      targetPort: 4566
    - name: web
      protocol: TCP
      port: 4510
      targetPort: 4510
  selector:
    app: localstack
  type: ClusterIP
