apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          ports:
            - containerPort: 4566
            - containerPort: 4510
          env:
            - name: DEBUG
              value: "1"
            - name: SERVICES
              value: "s3,web"
            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_SECRET_ACCESS_KEY
              value: test
            - name: EDGE_PORT
              value: "4566"
          volumeMounts:
            - name: localstack-data
              mountPath: /var/lib/localstack
      volumes:
        - name: localstack-data
          persistentVolumeClaim:
            claimName: localstack-pvc
