name: Build and Publish Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: EuroStocks/Dockerfile
          target: build
          load: true
      -
        name: Push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: EuroStocks/Dockerfile
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/eurostocks-api:latest

      -
        name: Build Consumers
        uses: docker/build-push-action@v5
        with:
          context: .
          file: EuroStocks.Consumers/Dockerfile
          target: build
          load: true
      -
        name: Push Consumers
        uses: docker/build-push-action@v5
        with:
          context: .
          file: EuroStocks.Consumers/Dockerfile
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/eurostocks-consumers:latest
